playbookname: 
host: 'webservers'
zone: 'Europe/Madrid'
rpms1: 'httpd-tools' 
rpms2: 'podman' 
rpms3: 'skopeo'
rpms4: 'openssl'
rpms5: 'passlib'
path: 'webserver'
podman_name: 'webserver'
container_name: 'web'
container_prefix: 'wservice'
tag_name: 'casopractico2'



