playbookname: 
host: 'webservers'
zone: 'Europe/Madrid'
rpms1: 'httpd-tools' 
rpms2: 'podman' 
rpms3: 'skopeo'
rpms4: 'openssl'
rpms5: 'passlib'
path: 'webserver'
podman_name: 'webserver'
container8s_name: 'aplicacion'
container_name: 'web'
container_prefix: 'wservice'
containerk8s_prefix: 'appservice'
tag_name: 'casopractico2'
podmank8s_name: 'jenkins/jenkins'
path_k8s: 'appi'

