---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: practica-k8s
spec:
  volumes:
    - name: pv-nginx
      persistentVolumeClaim:
        claimName: pvc-nginx
  containers:
    - name: pv-nginx-container
      image: practica2acr.azurecr.io/nginx:casopractico2
      ports:
        - containerPort: 80
          name: "nginx"
      volumeMounts:
        - mountPath: "/usr/share/nginx"
          name: pv-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: pv-nginx
  namespace: practica-k8s
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx-storage
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
  namespace: practica-k8s
spec:
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
