apiVersion: v1
kind: Deployment
metadata:
  name: persistent-storage
  namespace: practica-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-storage
  template:
    metadata:
      labels:
        app: jenkins-storage
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
        - name: jenkins-pv-storage
          persistentVolumeClaim:
            claimName: jenkins-storage
      containers:
      - name: jenkins-storage
        image: https://hub.docker.com/r/jenkins/jenkins
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
          name: "jenkins-ejemplo"
        volumeMounts:
          - mountPath: "/usr/share/jenkins"
            name: jenkins-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-storage
  namespace: practica-k8s
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: jenkins-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  namespace: practica-k8s
spec:
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
