---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: practica-k8s
spec:
  volumes:
    - name: pv-jenkins
      persistentVolumeClaim:
        claimName: pvc-jenkins
  containers:
    - name: pv-jenkins-container
      image: nginx
      ports:
        - containerPort: 8080
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/jenkins"
          name: pv-jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: pv-jenkins
  namespace: practica-k8s
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: jenkins-storage
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  namespace: practica-k8s
spec:
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
