---
- name: 'playbook login podman with acr'
  hosts: "{{host}}"
  remote_user: "{{ssh_user.value}}"
  become: true
  vars_files:
    - vars/vars.yaml
    - vars/outputs.json
  tasks:

    - name: Login to default registry with outputs.json
      containers.podman.podman_login:
        username: "{{acr_admin_user.value}}"
        password: "{{acr_admin_pass.value}}"
        registry: "{{acr_login_server.value}}"