---
- name: 'playbook instala podman en vm'
  hosts: "{{host}}"
  remote_user: "{{ssh_user.value}}"
  become: true
  vars_files:
    - vars/vars.yaml
    - vars/outputs.json
  tasks:

    - name: 'instalo podman'
      yum:
        name: "{{ rpms2 }}"
        state: latest

   